-- MySQL Script generated by MySQL Workbench
-- 08/04/16 14:08:44
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema acquygiakhangdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema acquygiakhangdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `acquygiakhangdb` DEFAULT CHARACTER SET utf8 ;
USE `acquygiakhangdb` ;

-- -----------------------------------------------------
-- Table `acquygiakhangdb`.`hangxe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `acquygiakhangdb`.`hangxe` (
  `MaHangXe` NVARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `TenHangXe` NVARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `GhiChu` NVARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`MaHangXe`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `acquygiakhangdb`.`loaixe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `acquygiakhangdb`.`loaixe` (
  `MaLoaiXe` NVARCHAR(45) NOT NULL,
  `TenLoaiXe` NVARCHAR(45) NULL DEFAULT NULL,
  `MaHangXe` NVARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`MaLoaiXe`),
  INDEX `fk_loaixe_hangxe1_idx` (`MaHangXe` ASC),
  CONSTRAINT `fk_loaixe_hangxe1`
    FOREIGN KEY (`MaHangXe`)
    REFERENCES `acquygiakhangdb`.`hangxe` (`MaHangXe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `acquygiakhangdb`.`dongxe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `acquygiakhangdb`.`dongxe` (
  `MaDongXe` NVARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `TenDongXe` NVARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `SoXyLanh` INT(11) NULL DEFAULT NULL,
  `DongCo` NVARCHAR(10) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `HopSo` NVARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `SoCua` INT(11) NULL DEFAULT NULL,
  `NhienLieu` NVARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `NamSanXuat` NVARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `MaLoaiXe` NVARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`MaDongXe`),
  INDEX `fk_dongxe_loaixe1_idx` (`MaLoaiXe` ASC),
  CONSTRAINT `fk_dongxe_loaixe1`
    FOREIGN KEY (`MaLoaiXe`)
    REFERENCES `acquygiakhangdb`.`loaixe` (`MaLoaiXe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `acquygiakhangdb`.`loainguoidung`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `acquygiakhangdb`.`loainguoidung` (
  `MaLoaiNguoiDung` INT(11) NOT NULL,
  `TenLoaiNguoiDung` NVARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `GhiChu` NVARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`MaLoaiNguoiDung`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `acquygiakhangdb`.`loaisanpham`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `acquygiakhangdb`.`loaisanpham` (
  `MaLoaiSanPham` INT(11) NOT NULL AUTO_INCREMENT,
  `TenLoaiSanPham` NVARCHAR(45) NULL DEFAULT NULL,
  `MaLoaiCha` INT(11) NULL DEFAULT NULL,
  `MucLoaiSanPham` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`MaLoaiSanPham`))
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `acquygiakhangdb`.`nguoidung`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `acquygiakhangdb`.`nguoidung` (
  `MaNguoiDung` NVARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `TenNguoiDung` NVARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `MatKhau` NVARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `MaLoaiNguoiDung` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`MaNguoiDung`),
  INDEX `MaLoaiNguoiDung_idx` (`MaLoaiNguoiDung` ASC),
  CONSTRAINT `MaLoaiNguoiDung`
    FOREIGN KEY (`MaLoaiNguoiDung`)
    REFERENCES `acquygiakhangdb`.`loainguoidung` (`MaLoaiNguoiDung`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `acquygiakhangdb`.`nhacungcap`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `acquygiakhangdb`.`nhacungcap` (
  `MaNhaCC` NVARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `TenNhaCC` NVARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `Email` NVARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `DienThoai` NVARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `DiaChi` NVARCHAR(100) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `GhiChu` NVARCHAR(100) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`MaNhaCC`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `acquygiakhangdb`.`quocgia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `acquygiakhangdb`.`quocgia` (
  `MaQuocGia` NVARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `TenQuocGia` NVARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `GhiChu` NVARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`MaQuocGia`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `acquygiakhangdb`.`tinhtrang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `acquygiakhangdb`.`tinhtrang` (
  `MaTinhTrang` NVARCHAR(45) NOT NULL,
  `TenTinhTrang` NVARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`MaTinhTrang`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `acquygiakhangdb`.`hinhanh`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `acquygiakhangdb`.`hinhanh` (
  `MaHinhAnh` INT NOT NULL AUTO_INCREMENT,
  `TenHinhAnh` NVARCHAR(100) NULL,
  `DuongDanHinhAnh` NVARCHAR(200) NULL,
  PRIMARY KEY (`MaHinhAnh`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `acquygiakhangdb`.`sanphamhinhanh`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `acquygiakhangdb`.`sanphamhinhanh` (
  `MaSanPham` NVARCHAR(45) NOT NULL,
  `MaHinhAnh` INT NOT NULL,
  PRIMARY KEY (`MaSanPham`, `MaHinhAnh`),
  INDEX `fk_sanphamhinhanh_hinhanh1_idx` (`MaHinhAnh` ASC),
  CONSTRAINT `fk_sanphamhinhanh_hinhanh1`
    FOREIGN KEY (`MaHinhAnh`)
    REFERENCES `acquygiakhangdb`.`hinhanh` (`MaHinhAnh`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `acquygiakhangdb`.`sanpham`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `acquygiakhangdb`.`sanpham` (
  `MaSanPham` NVARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `TenSanPham` NVARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `MoTa` NVARCHAR(100) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `Gia` NVARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `MaTinhTrang` NVARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `HinhDaiDien` NVARCHAR(100) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `MaNhaCC` NVARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `MaQuocGia` NVARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `MaLoaiSanPham` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`MaSanPham`),
  INDEX `MaNhaCC_idx` (`MaNhaCC` ASC),
  INDEX `MaQuocGia_idx` (`MaQuocGia` ASC),
  INDEX `MaLoaiSanPham_idx` (`MaLoaiSanPham` ASC),
  INDEX `fk_sanpham_tinhtrang1_idx` (`MaTinhTrang` ASC),
  CONSTRAINT `MaLoaiSanPham`
    FOREIGN KEY (`MaLoaiSanPham`)
    REFERENCES `acquygiakhangdb`.`loaisanpham` (`MaLoaiSanPham`),
  CONSTRAINT `MaNhaCC`
    FOREIGN KEY (`MaNhaCC`)
    REFERENCES `acquygiakhangdb`.`nhacungcap` (`MaNhaCC`),
  CONSTRAINT `MaQuocGia`
    FOREIGN KEY (`MaQuocGia`)
    REFERENCES `acquygiakhangdb`.`quocgia` (`MaQuocGia`),
  CONSTRAINT `MaTinhTrang`
    FOREIGN KEY (`MaTinhTrang`)
    REFERENCES `acquygiakhangdb`.`tinhtrang` (`MaTinhTrang`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sanpham_sanphamhinhanh1`
    FOREIGN KEY (`MaSanPham`)
    REFERENCES `acquygiakhangdb`.`sanphamhinhanh` (`MaSanPham`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `acquygiakhangdb`.`sanphamdongxe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `acquygiakhangdb`.`sanphamdongxe` (
  `MaSanPham` NVARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `MaDongXe` NVARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `MoTa` NVARCHAR(100) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`MaSanPham`, `MaDongXe`),
  INDEX `MaDongXe_idx` (`MaDongXe` ASC),
  CONSTRAINT `MaDongXe`
    FOREIGN KEY (`MaDongXe`)
    REFERENCES `acquygiakhangdb`.`dongxe` (`MaDongXe`),
  CONSTRAINT `MaSanPham`
    FOREIGN KEY (`MaSanPham`)
    REFERENCES `acquygiakhangdb`.`sanpham` (`MaSanPham`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
